sudo: required
# dist: xenial
services:

language: go

go:
  - 1.10

os:
  - linux
  - osx

env:
  matrix:
    - TARGETS="ci"
    - TARGETS="crosscompile"

  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"
    - DOCKER_COMPOSE_VERSION: 1.9.0

matrix:
  include:
    - os: osx
      python: "2.7"
      env: TARGETS="ci"
      before_install:
          - pip install -U pip && pip install virtualenv
          - brew update && brew upgrade pyenv
          - pyenv install -f 2.7.15
          - pip install virtualenv
          - virtualenv -p ~/.pyenv/versions/2.7.15/bin/python ./env
          - source env/bin/activate
    - os: linux
      python: "2.7"

matrix:
  exclude:
    - os: osx
      env: TARGETS="crosscompile"

addons:
  apt:
    packages:
      - python-virtualenv
  homebrew:
    packages:
      - python-virtualenv

before_install:
  # Redo the travis setup but with the edgarm1964/execbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/edgarm1964/execbeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/edgarm1964/execbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/edgarm1964/execbeat
  - chmod -R go-w $HOME/gopath/src/github.com/edgarm1964/execbeat
  - cd $HOME/gopath/src/github.com/edgarm1964/execbeat
  - make add-headers

  # install govendor
  - go get github.com/kardianos/govendor
  - go install github.com/kardianos/govendor

  # install osx specific elements
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew upgrade pyenv; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip install virtualenv; fi

install:
  - true

script:
  - make $TARGETS

after_success:
 - test -f build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f build/coverage/full.cov
