// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("execbeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy0WF1v3LoRffevGOQpAdZCYzdGsQ9FUydojDZt0CTPm1lyVuK1RCrkyPbeX3/BD31Z2g9n974YK4o853B4ZobyJdzTdgn0RGJNyBcArLik0YgkJ6yqWRm9hI9pPExomBwIU1WopQPUEhz5X1wQmIbrhl+7N2GcnhSDMJKADVCJjpVwhFYUYCyUJneMrsguADaKSumWFwAAl6CxSmLCAABva1pCbk1Tp5HhguGipKsbb9cyPfFgcLS7vw9eAHwrqEVptythve1ikF1MSB1L0/AJnF8ZtUQrU/ygtkY2IvLyL+kha8+hh6w19lQ53ga3RtJEkNJMOdnjNH3szGQ2x6hIJh8b/J8z5o40t0YzKh2dbXRYl1wG+ICqxHVJoDRgWQI9kOawCTd078i+QYb/ebF3a95ufla7K68wJJTSeRgoTQ4VOYc5uQzuBrPCMuU6KEfsBcbY6I3KG4ueDjaqpIUf9y+R4QHLxq+ExpEMmIr9ozY8BAtLoDCOE1Oa/80EqpGOhX8Xhn74xx8djgk73q0rmwatZTwcuE4bOrDEjdW9SU1Nnkbn4LaOqQKj4bFQouiFD2JnG62VzmfUsKrod6OPUNPO/DPVPJB1yujDYtLE1lbBzuHwc9JeCkngQrlo5Wxs3Vf/8FtxjFX9alSBJXIbB0s/G2VJLoFt0w5ujK2QR/PoCavap977Jm8cw9UNF3D1l7c3C3h7tbx+t3x3nV1fXx0X3SAJHqORKaWhTxBLwlgJj+j6/T3bFGPu9rO8t2vFFu02zI3REuhLQfB7TTYelC86/oEtaoeC+/OIcXpGHKvDKI5m/RuJNtfiwyq+uafto7Fyv9CuVjWObJ9TvkBFsmcKQhXf2Up3kHwMpT9VQBEZvX9RSuXnYglKb4zPbIEu1K/A47IDLToVsxPaU5SWcLKZO8BMrymNzl+C7kGm0B5rAj0+s6PQo01SixKlaWTfo279o++5D0qS3yajRMb5tvU5vYWNNVVE6pY6f1Z9CUIpV2HCqoX0MwU5Z+zOLuanZmFV1sI+T2wSB7L3v4P2NlaYwRfjnPLGDT3JAVrygAvIBS38LVGqXDGWRhDqbKc2pR2jFrRSB1LnLk2Euw+tJN9EoEJRKP08decYDnemjmPY149jSRNWA591cearrCKpmmo/++cIESz2MvJ0zVGl4u1q0PI6BY27JHR8+VYcKKQDIAgdUfXdTrkoR7m+ze2xXKiN3al2UtKby6fjrZeWeC3/MiYvKWbabnZL+cFW+/8w59D+UqJLI+5D/qRM/9A+z4DHd+AY2ZffsiThe3ZI8/jO56wrjOVV7ABL2GDp/KGhFoWxLd9ll+U7PrQ6WfDCT63QE8hmavq99aKa+F2rnw31gKDkXFXv6Kq59vEixqEvAlx7O00C/EVi3aiSweh9UgbF4BeV3HacHmsfV4lrKt2EbXSXgP33iQNa7kIkIk9nWm/m3rKf4tMMyJ2/DAyM6rvcpPT03vTjB52ZuF/my9PP5FP6rJiexpmcHgvEjMnRikIxCW7sGfYwgoPXlOUZPP3tZnXz1wWgrRZQ12IBlardm6kU47K6RPZX+tOU/O8rtEBJgyDNxi2gWTeamwU8Ki3N4w4R4y+eX9eQcGY5NlipcnsyRYRJm7QkC+QFSFor1AvYWKK1k/t2q+qJhNHQHvb/KMe+oN19uUQpLTlHbkpQoThtky1NgVY+oqWebAGNa7Ast/D5/e1QQ1tH7ps1WU1Mrq8m/x6OzdD277tr8PhO24PCsJbsb4v9ooMFaCQaXlSGaiPP0B4GEaiNjLVtlqo5tTQNmL4YCd/vPkyJ/F9XozjfpnrEKZn/AjtrBD3ijhAe21yPI4poUGE9ZUKtDYf/f52NbgA5z3nOC8uAV4zuLvtoz3Blm+WNuH8EAAD//yIEQ3o="
}
